### PR TITLE
Add SimpleInjector to supported Containers

### PR DESCRIPTION
**Pull request by GuyHarwood**
Added project for SimpleInjector IOC container
created tests
Added NuSpec

### CODE REVIEW

**Comment by patroza** [comment]
Neat! I came across this little gem (SimpleInjector) recently too and ever since been keen on adopting it, actually had written the dependency resolver already minus tests and nuspec, so this is great :)

**Comment by GuyHarwood** [comment]
Good stuff, Glad you find it useful.  Wondering if anyone in charge is getting PR notifications as it's been sat here a while!

**Comment by patroza** [comment]
Yea I got a bunch open still as well ;-)
I would be happy to merge it into my fork https://github.com/sickboy/ShortBus

**Comment by GuyHarwood** [comment]
I'll try and get in touch with the owner, see if he is still interested in it.  Will send you a PR if I can do that, not sure if it's possible?

**Pull request merged**
